Repository team-withUs/withUs, pull requests merged in 2024-02, with the labels that each got.

#215 Docker-compose.yaml 파일, gradle.yaml 파일 수정
  .github/workflows/gradle.yaml
  docker-compose.yaml
  src/test/java/com/withus/withus/chat/service/ChatRoomServiceIntegrationTest.java
  src/test/java/com/withus/withus/club/service/ClubServiceImplTest.java
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: enhancement

#214 #210 코드 Refactoring fix0.1
  src/main/java/com/withus/withus/domain/club/repository/ClubRepositoryQueryImpl.java
  src/main/java/com/withus/withus/domain/comment/controller/CommentController.java
  src/main/java/com/withus/withus/domain/comment/repository/CommentRepository.java
  src/main/java/com/withus/withus/domain/comment/service/CommentService.java
  src/main/java/com/withus/withus/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/withus/withus/domain/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/domain/notice/controller/NoticeViewController.java
  src/main/java/com/withus/withus/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/withus/withus/global/scheduler/DeleteScheduler.java
  src/main/resources/templates/notice/noticeDetail.html
Labels: refactor

#220 #210 코드 Refactoring fix0.2
  src/main/java/com/withus/withus/global/scheduler/DeleteScheduler.java
Labels: fix
