Repository team-withUs/withUs, pull requests merged in 2024-01, with the labels that each got.

#14 properties 초기 설정 및 Email 인증코드 발송 구현
  build.gradle
  src/main/java/com/withus/withus/club/entity/Club.java
  src/main/java/com/withus/withus/comment/entity/Comment.java
  src/main/java/com/withus/withus/global/Response/ResponseCode.java
  src/main/java/com/withus/withus/global/config/EmailConfig.java
  src/main/java/com/withus/withus/global/config/RedisConfig.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/response/CommonResponse.java
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/global/timestamp/TimeStamp.java
  src/main/java/com/withus/withus/global/utils/EmailService.java
  src/main/java/com/withus/withus/global/utils/RedisService.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/dto/EmailRequestDto.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/repository/MemberRepository.java
  src/main/java/com/withus/withus/member/service/MemberService.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/repository/NoticeRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/application-product.properties
  src/main/resources/application-test.properties
  src/main/resources/application.properties
Labels: enhancement

#18 add : 회원 프로필 보기 구현
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/dto/MemberResponseDto.java
  src/main/java/com/withus/withus/member/service/MemberService.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: enhancement

#21 fix : 인가 오류 수정
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: fix

#20 Feature/notice
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/notice/dto/NoticeRequestDto.java
  src/main/java/com/withus/withus/notice/dto/NoticeResponseDto.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/repository/NoticeRepository.java
  src/main/java/com/withus/withus/notice/service/NoticeService.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
Labels: enhancement

#22 fix : 인가 오류 수정2
  src/main/java/com/withus/withus/global/security/CustomLogoutHandler.java
  src/main/java/com/withus/withus/global/security/UserDetailsImpl.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtUtil.java
  src/main/java/com/withus/withus/global/security/jwt/RefreshToken.java
  src/main/java/com/withus/withus/global/security/jwt/RefreshTokenRepository.java
Labels: fix

#30 #23 업데이트 API 구현
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/service/NoticeService.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
Labels: enhancement

#29 add : 회원 프로필 수정 추가
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/dto/MemberResponseDto.java
  src/main/java/com/withus/withus/member/dto/UpdateRequestDto.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/service/MemberService.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: enhancement

#39 add : @AuthenticationPrincipal to Member 변환 추가
  src/main/java/com/withus/withus/global/annotation/AuthMember.java
Labels: enhancement

#38 #37 add : 회원 신고하기 기능 추가
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/service/MemberService.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: enhancement

#36 #24 , #25 #27 기능 API 구현
  src/main/java/com/withus/withus/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/repository/NoticeRepository.java
  src/main/java/com/withus/withus/notice/service/NoticeService.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
Labels: enhancement

#43 #26 전체조회 API 구현 , #11 게시판생성에 클럽추가
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/notice/dto/PageableDto.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/repository/NoticeRepository.java
  src/main/java/com/withus/withus/notice/service/NoticeService.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
Labels: enhancement

#44 Comment entity 작성
  src/main/java/com/withus/withus/comment/controller/CommentController.java
  src/main/java/com/withus/withus/comment/controller/controller.java
  src/main/java/com/withus/withus/comment/dto/CommentRequestDto.java
  src/main/java/com/withus/withus/comment/dto/CommentResponseDto.java
  src/main/java/com/withus/withus/comment/entity/Comment.java
  src/main/java/com/withus/withus/global/timestamp/TimeStamp.java
Labels: enhancement

#50 #46, #47, #49 add : 내 클럽 목록 불러오기 , 클럽 초대, 신고기능 수정
  src/main/java/com/withus/withus/club/entity/ClubMember.java
  src/main/java/com/withus/withus/club/entity/ClubMemberRole.java
  src/main/java/com/withus/withus/club/repository/ClubMemberRepository.java
  src/main/java/com/withus/withus/club/service/ClubMemberService.java
  src/main/java/com/withus/withus/club/service/ClubMemberServiceImpl.java
  src/main/java/com/withus/withus/club/service/ClubService.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/comment/dto/CommentResponseDto.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/response/ResponseCode.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/dto/ReportRequestDto.java
  src/main/java/com/withus/withus/member/dto/UpdateRequestDto.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/entity/ReportMember.java
  src/main/java/com/withus/withus/member/repository/MemberRepository.java
  src/main/java/com/withus/withus/member/repository/ReportMemberRepository.java
  src/main/java/com/withus/withus/member/service/MemberService.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: enhancement

#48 #11, #23, # 24, #26, #27 전체 url 수정 그리고 클럽아이디 존재 확인추가
  src/main/java/com/withus/withus/club/repository/ClubRepository.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/notice/dto/ReportRequestDto.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/entity/NoticeCategory.java
  src/main/java/com/withus/withus/notice/entity/ReportNotice.java
  src/main/java/com/withus/withus/notice/repository/ReportRepository.java
  src/main/java/com/withus/withus/notice/service/NoticeService.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
Labels: enhancement

#52 #11, #23, #24 클럽멤버만 사용할수있게 구현 그리고 생성에 카테고리 추가
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/notice/dto/NoticeRequestDto.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
Labels: enhancement

#54 #53 add : S3 설정 및 참조 수정
  build.gradle
  src/main/java/com/withus/withus/club/service/ClubMemberService.java
  src/main/java/com/withus/withus/club/service/ClubMemberServiceImpl.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/exception/GlobalExceptionHandler.java
  src/main/java/com/withus/withus/global/s3/S3Config.java
  src/main/java/com/withus/withus/global/s3/S3Const.java
  src/main/java/com/withus/withus/global/s3/S3Util.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/dto/MemberResponseDto.java
  src/main/java/com/withus/withus/member/dto/UpdateRequestDto.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#56 #5,#6,#7,#8,#9 채팅 기능 구현
  build.gradle
  src/main/java/com/withus/withus/chat/controller/ChatMessageController.java
  src/main/java/com/withus/withus/chat/controller/ChatRoomController.java
  src/main/java/com/withus/withus/chat/dto/ChatMessagePageListResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatPostDto.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomPageListResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/withus/withus/chat/dto/MessageDto.java
  src/main/java/com/withus/withus/chat/entity/ChatMessage.java
  src/main/java/com/withus/withus/chat/entity/ChatRoom.java
  src/main/java/com/withus/withus/chat/repository/ChatMessageRepository.java
  src/main/java/com/withus/withus/chat/repository/ChatRoomRepository.java
  src/main/java/com/withus/withus/chat/service/ChatMessageService.java
  src/main/java/com/withus/withus/chat/service/ChatRoomService.java
  src/main/java/com/withus/withus/global/config/RedisConfig.java
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/java/com/withus/withus/global/config/WebSocketConfig.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/response/PageInfo.java
  src/main/java/com/withus/withus/global/security/UserDetailsServiceImpl.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/dto/ChatMemberResponseDto.java
  src/main/java/com/withus/withus/member/repository/MemberRepository.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: enhancement

#57 fix : 파일첨부 관련 수정
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: fix

#62 채팅방 기능 구현 완료 및 테스트 코드 작성
  src/main/java/com/withus/withus/chat/controller/ChatRoomController.java
  src/main/java/com/withus/withus/chat/dto/ChatMessagePageListResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomPageListResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/withus/withus/chat/dto/MessageDto.java
  src/main/java/com/withus/withus/chat/entity/ChatMessage.java
  src/main/java/com/withus/withus/chat/entity/ChatRoom.java
  src/main/java/com/withus/withus/chat/repository/ChatRoomRepository.java
  src/main/java/com/withus/withus/chat/service/ChatMessageService.java
  src/main/java/com/withus/withus/chat/service/ChatRoomService.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/member/dto/ChatMemberResponseDto.java
  src/main/java/com/withus/withus/member/dto/MemberResponseDto.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/entity/ReportMember.java
  src/test/java/com/withus/withus/chat/service/ChatRoomServiceIntegrationTest.java
Labels: enhancement, test

#60 #59 를 #11, #23 에 추가 : 게시판 생성, 수정에서 s3 추가
  src/main/java/com/withus/withus/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/notice/dto/NoticeRequestDto.java
  src/main/java/com/withus/withus/notice/dto/NoticeResponseDto.java
  src/main/java/com/withus/withus/notice/entity/Notice.java
  src/main/java/com/withus/withus/notice/repository/ReportRepository.java
  src/main/java/com/withus/withus/notice/service/NoticeServiceImpl.java
  src/test/java/com/withus/withus/notice/service/NoticeServiceImplTest.java
Labels: enhancement

#64 #63, test : 멤버 테스트(멤버 정보 불러오기 ~ 멤버 초대)
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/member/entity/ReportMember.java
  src/main/java/com/withus/withus/member/repository/ReportMemberRepository.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: test

#69 삭제할 부분 삭제
  src/main/java/com/withus/withus/category/entity/ClubCategory.java
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/club/repository/ClubRepository.java
  src/main/java/com/withus/withus/club/service/ClubService.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
Labels: enhancement

#71 클럽 검색 구현
  build.gradle
  src/main/java/com/withus/withus/HomeController.java
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/club/repository/ClubRepository.java
  src/main/java/com/withus/withus/club/repository/ClubRepositoryQuery.java
  src/main/java/com/withus/withus/club/repository/ClubRepositoryQueryImpl.java
  src/main/java/com/withus/withus/club/service/ClubService.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/global/config/JPAConfiguration.java
  src/test/java/com/withus/withus/club/service/ClubServiceImplTest.java
Labels: enhancement

#73 인증로직 변경 및 chat front 수정
  src/main/java/com/withus/withus/chat/controller/ChatMessageController.java
  src/main/java/com/withus/withus/chat/controller/ChatRoomController.java
  src/main/java/com/withus/withus/chat/controller/ChatViewController.java
  src/main/java/com/withus/withus/chat/dto/ChatMessagePageListResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatMessageResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatPostDto.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomPageListResponseDto.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/withus/withus/chat/dto/MessageDto.java
  src/main/java/com/withus/withus/chat/entity/ChatMessage.java
  src/main/java/com/withus/withus/chat/entity/ChatRoom.java
  src/main/java/com/withus/withus/chat/repository/ChatMessageRepository.java
  src/main/java/com/withus/withus/chat/repository/ChatRoomRepository.java
  src/main/java/com/withus/withus/chat/service/ChatMessageService.java
  src/main/java/com/withus/withus/chat/service/ChatRoomService.java
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/java/com/withus/withus/global/config/WebSocketConfig.java
  src/main/java/com/withus/withus/global/security/CustomLogoutHandler.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtUtil.java
  src/main/java/com/withus/withus/member/controller/MemberViewController.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/img/background.jpg
  src/main/resources/static/img/cat.jpg
  src/main/resources/static/img/default.png
  src/main/resources/static/img/invite.png
  src/main/resources/static/img/message.png
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/chat/chatRoomList.html
  src/main/resources/templates/header/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/loginPage.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
  src/test/java/com/withus/withus/chat/service/ChatRoomServiceIntegrationTest.java
Labels: enhancement, fix

#74 add : 로그인,회원가입,프로필,프로필 수정, 메인 일부 구현 프론트
  src/main/java/com/withus/withus/HomeController.java
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/controller/MemberViewController.java
  src/main/java/com/withus/withus/member/dto/MemberResponseDto.java
  src/main/java/com/withus/withus/member/dto/UpdateRequestDto.java
  src/main/java/com/withus/withus/member/entity/Member.java
  src/main/java/com/withus/withus/member/service/MemberService.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/resources/static/css/Bootstrap.min.css
  src/main/resources/static/img/icon-search.png
  src/main/resources/templates/clubPage.html
  src/main/resources/templates/index.html
  src/main/resources/templates/loginPage.html
  src/main/resources/templates/noticedetail.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/signupPage.html
  src/main/resources/templates/updateProfile.html
Labels: enhancement, fix

#84 feature, fix : 인증로직 일부 수정, index.html 헤더부분 기능 추가
  src/main/java/com/withus/withus/chat/controller/ChatViewController.java
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/security/UserDetailsServiceImpl.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtUtil.java
  src/main/java/com/withus/withus/member/controller/MemberViewController.java
  src/main/java/com/withus/withus/member/repository/MemberRepository.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/resources/application-product.properties
  src/main/resources/static/img/cat.jpg
  src/main/resources/static/img/create.png
  src/main/resources/static/img/myInfo.png
  src/main/resources/static/index.html
  src/main/resources/templates/auth/loginPage.html
  src/main/resources/templates/auth/signupPage.html
  src/main/resources/templates/header/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: enhancement, fix

#92 fix : 프로필 프론트 페이지 수정
  src/main/java/com/withus/withus/global/security/CustomLogoutHandler.java
  src/main/resources/static/img/logout.png
  src/main/resources/templates/auth/loginPage.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: fix

#95 feat : 클럽 생성,조회,수정,삭제 페이지 연결 및 헤더 생성
  src/main/java/com/withus/withus/club/controller/ClubViewController.java
  src/main/resources/static/css/clubpost.css
  src/main/resources/static/css/clubrevise.css
  src/main/resources/static/css/clubstyle.css
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/clubPage.html
  src/main/resources/templates/index.html
Labels: enhancement

#104 클럽 프론트 css 수정
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/club/dto/InviteMemberResponseDto.java
  src/main/resources/static/css/clubstyle.css
  src/main/resources/static/js/getclub.js
  src/main/resources/templates/club/main-club.html
Labels: enhancement, fix

#112 fix : chat 프론트 수정
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/chat/chatRoomList.html
Labels: fix

#115 Feature/memberfix : 카테고리 검색 결과 없을 시 생기던 에러 수정, 프로필 수정 에러페이지 수정
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/updateProfile.html
Labels: fix

#120 feat : 채팅창에서 프로필이동기능
  src/main/java/com/withus/withus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/withus/withus/chat/service/ChatRoomService.java
  src/main/resources/templates/chat/chatRoom.html
Labels: enhancement

#121 feat : 리프레시토큰 삭제 스케쥴러 구현
  src/main/java/com/withus/withus/global/scheduler/Scheduler.java
Labels: enhancement

#123 fix : 이메일 인증 패스 삭제
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
Labels: fix

#124 fix : 채팅방 프로필 조회 이슈 수정
  src/main/java/com/withus/withus/chat/dto/ChatRoomResponseDto.java
  src/main/resources/templates/chat/chatRoom.html
Labels: fix

#126 fix : 검색 후 카테고리 변경 시 카테고리 적용, 메인페이지 css 변경, url로 다른 유저 프로필 수정 접근 방지, 에러 메세지 출력
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/member/controller/MemberViewController.java
  src/main/resources/templates/auth/signupPage.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myClub.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: fix

#129 fix : 클럽 목록 페이지네이션 수정, 내 클럽 목록조회 코드 수정
  src/main/java/com/withus/withus/club/repository/ClubMemberRepository.java
  src/main/java/com/withus/withus/club/service/ClubMemberServiceImpl.java
  src/main/resources/templates/index.html
Labels: fix

#136 #135 수정
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/club/repository/ClubRepositoryQuery.java
  src/main/java/com/withus/withus/club/repository/ClubRepositoryQueryImpl.java
  src/main/java/com/withus/withus/club/service/ClubService.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/resources/templates/index.html
  src/test/java/com/withus/withus/club/service/ClubServiceImplTest.java
Labels: enhancement

#140 #137 fix : MemberViewController url 수정 및 메인페이지 페이지네이션 수정, 클럽조회 목룩 반환타임 Page로 수정
  src/main/java/com/withus/withus/HomeController.java
  src/main/java/com/withus/withus/club/controller/ClubController.java
  src/main/java/com/withus/withus/club/repository/ClubMemberRepository.java
  src/main/java/com/withus/withus/club/repository/ClubRepository.java
  src/main/java/com/withus/withus/club/repository/ClubRepositoryQuery.java
  src/main/java/com/withus/withus/club/repository/ClubRepositoryQueryImpl.java
  src/main/java/com/withus/withus/club/service/ClubMemberServiceImpl.java
  src/main/java/com/withus/withus/club/service/ClubService.java
  src/main/java/com/withus/withus/club/service/ClubServiceImpl.java
  src/main/java/com/withus/withus/member/controller/MemberViewController.java
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
Labels: fix

#141 fefactor, fix, feat : 채팅 API URL 수정, 채팅방내 프로필사진 구현, createRoom 오타 수정
  src/main/java/com/withus/withus/chat/controller/ChatMessageController.java
  src/main/java/com/withus/withus/chat/controller/ChatRoomController.java
  src/main/java/com/withus/withus/chat/controller/ChatViewController.java
  src/main/java/com/withus/withus/chat/dto/ChatRoomResponseDto.java
  src/main/java/com/withus/withus/chat/entity/ChatRoom.java
  src/main/java/com/withus/withus/chat/service/ChatMessageService.java
  src/main/java/com/withus/withus/chat/service/ChatRoomService.java
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/chat/chatRoomList.html
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
  src/test/java/com/withus/withus/chat/service/ChatRoomServiceIntegrationTest.java
Labels: enhancement, fix, refactor

#144 클럽멤버 호스트권한 queryDSL로 수정
  src/main/java/com/withus/withus/club/repository/ClubMemberRepository.java
  src/main/java/com/withus/withus/club/repository/ClubMemberRepositoryQuery.java
  src/main/java/com/withus/withus/club/repository/ClubMemberRepositoryQueryImpl.java
  src/main/java/com/withus/withus/club/service/ClubMemberServiceImpl.java
  src/main/java/com/withus/withus/comment/controller/CommentController.java
  src/main/java/com/withus/withus/comment/dto/CommentDeleteRequestDto.java
  src/main/java/com/withus/withus/comment/dto/CommentRequestDto.java
  src/main/java/com/withus/withus/comment/service/CommentService.java
  src/main/java/com/withus/withus/comment/service/CommentServiceImpl.java
  src/main/resources/templates/notice/noticeDetail.html
Labels: enhancement

#145 add, fix : 알림기능 구현, url 관련 수정, 회원 탈퇴기능 추가
  src/main/generated/com/withus/withus/club/entity/QClub.java
  src/main/java/com/withus/withus/chat/controller/ChatMessageController.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/java/com/withus/withus/notification/controller/NotificationController.java
  src/main/java/com/withus/withus/notification/dto/NotifiationDto.java
  src/main/java/com/withus/withus/notification/service/NotificationService.java
  src/main/resources/static/js/getclub.js
  src/main/resources/static/js/sse.js
  src/main/resources/templates/auth/loginPage.html
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: enhancement, fix

#148 feat, fix : 회원가입간소화(email인증패스), 버그 수정
  src/main/java/com/withus/withus/WithUsApplication.java
  src/main/java/com/withus/withus/global/config/RedisConfig.java
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/resources/templates/auth/loginPage.html
  src/main/resources/templates/chat/chatRoomList.html
Labels: enhancement, fix

#151 #132 테스트 코드 수정
  src/main/resources/static/css/clubstyle.css
  src/main/resources/templates/club/main-club.html
  src/test/java/com/withus/withus/club/service/ClubServiceImplTest.java
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: enhancement

#153 CI/CD 최신화
  .github/workflows/gradle.yaml
  Dockerfile
  docker-compose.yaml
  src/main/generated/com/withus/withus/club/entity/QClub.java
  src/main/resources/application-product.properties
  src/main/resources/application.properties
  src/test/java/com/withus/withus/chat/service/ChatRoomServiceIntegrationTest.java
  src/test/java/com/withus/withus/club/service/ClubServiceImplTest.java
  src/test/java/com/withus/withus/notice/service/NoticeServiceImplTest.java
Labels: enhancement

#156 노티스 디테일 페이지 수정 과 #150 삭제 스케줄러 구현
  src/main/java/com/withus/withus/WithUsApplication.java
  src/main/java/com/withus/withus/club/repository/ClubMemberRepository.java
  src/main/java/com/withus/withus/club/repository/ClubRepository.java
  src/main/java/com/withus/withus/comment/repository/CommentRepository.java
  src/main/java/com/withus/withus/global/scheduler/DeleteScheduler.java
  src/main/java/com/withus/withus/member/repository/MemberRepository.java
  src/main/java/com/withus/withus/notice/repository/NoticeRepository.java
  src/main/resources/templates/notice/noticeDetail.html
  src/test/java/com/withus/withus/notice/service/NoticeServiceImplTest.java
Labels: enhancement

#157 feat, fix : 중복로그인 막는 로직 구현, 모든 token redis로 이관, 버그 픽스
  src/main/java/com/withus/withus/chat/controller/ChatMessageController.java
  src/main/java/com/withus/withus/global/config/WebSecurityConfig.java
  src/main/java/com/withus/withus/global/exception/ErrorCode.java
  src/main/java/com/withus/withus/global/scheduler/Scheduler.java
  src/main/java/com/withus/withus/global/security/CustomLogoutHandler.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtUtil.java
  src/main/java/com/withus/withus/global/security/jwt/RefreshToken.java
  src/main/java/com/withus/withus/global/security/jwt/RefreshTokenRepository.java
  src/main/java/com/withus/withus/global/utils/RedisService.java
  src/main/resources/static/js/getclub.js
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/profile.html
Labels: bug, enhancement

#162 fix : 버그 수정
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: bug

#165 #152 buttonContainer 정렬
  src/main/generated/com/withus/withus/global/security/jwt/QRefreshToken.java
  src/main/resources/templates/profile.html
Labels: enhancement

#167 fix : 클럽 최신순 조회, 클럽 초대 페이지 수정, 파일 용량 제한 1MB
  src/main/java/com/withus/withus/club/repository/ClubMemberRepository.java
  src/main/java/com/withus/withus/club/service/ClubMemberServiceImpl.java
  src/main/java/com/withus/withus/member/controller/MemberViewController.java
  src/main/resources/application.properties
  src/main/resources/templates/auth/signupPage.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myClub.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: fix

#168 fix : 네트워크 트래픽 다이어트(BootStrap패키지파일에서 CDN으로 수정)
  src/main/resources/templates/auth/loginPage.html
  src/main/resources/templates/auth/signupPage.html
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/chat/chatRoomList.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myClub.html
  src/main/resources/templates/notice/noticeDetail.html
  src/main/resources/templates/noticedetail.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: fix

#170 fix, refactor : 부트스트랩패키지 삭제, accessToken 재발급시 에러반환로직에서 정상수행로직으로 변경
  src/main/java/com/withus/withus/global/security/jwt/JwtAuthorizationFilter.java
  src/main/java/com/withus/withus/global/security/jwt/JwtUtil.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/js/getclub.js
Labels: enhancement, fix

#171 fix : 멤버 프로필 수정 오류 개선, 이미지 링크 수정
  src/main/java/com/withus/withus/member/dto/SignupRequestDto.java
  src/main/java/com/withus/withus/member/dto/UpdateRequestDto.java
  src/main/java/com/withus/withus/member/service/MemberServiceImpl.java
  src/main/resources/static/icons/comment-check_5068752.png
  src/main/resources/static/icons/icons8-돋보기-24.png
  src/main/resources/static/icons/icons8-취소-30.png
  src/main/resources/static/icons/icons8-확인.gif
  src/main/resources/static/icons/image.png
  src/main/resources/static/icons/noties.png
  src/main/resources/static/icons/search_3031293.png
  src/main/resources/static/icons/수정.png
  src/main/resources/static/img/arrow_10940959.png
  src/main/resources/static/img/background.jpg
  src/main/resources/static/img/create.png
  src/main/resources/static/img/default.png
  src/main/resources/static/img/icon-search.png
  src/main/resources/static/img/invite.png
  src/main/resources/static/img/logout.png
  src/main/resources/static/img/message.png
  src/main/resources/static/img/myInfo.png
  src/main/resources/static/img/myclub.png
  src/main/resources/static/js/getclub.js
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myClub.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: fix

#172 category, darkmodebtn, css 수정
  src/main/java/com/withus/withus/member/controller/MemberController.java
  src/main/resources/static/css/clubpost.css
  src/main/resources/static/css/clubrevise.css
  src/main/resources/static/css/clubstyle.css
  src/main/resources/static/js/clubpost.js
  src/main/resources/static/js/clubrevise.js
  src/main/resources/static/js/getclub.js
  src/main/resources/templates/chat/chatRoomList.html
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/index.html
  src/main/resources/templates/myClub.html
  src/main/resources/templates/notice/noticeAdd.html
  src/main/resources/templates/notice/noticeDetail.html
  src/main/resources/templates/notice/noticeEdit.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: enhancement

#178 fix : 상대경로수정 누락부분 추가(loginPage)
  src/main/resources/templates/auth/loginPage.html
Labels: fix

#183 fix : chatRoom 알림기능 memberId -> loginId 수정
  src/main/resources/templates/chat/chatRoom.html
Labels: fix

#196 #32 cateory 오류 수정
  src/main/resources/static/js/clubpost.js
Labels: fix

#197 category 오류 수정
  src/main/resources/static/js/clubpost.js
Labels: fix

#205 feat : 유저 피드백 반영 기능 개선
  src/main/java/com/withus/withus/WithUsApplication.java
  src/main/java/com/withus/withus/domain/chat/dto/MessageDto.java
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
  src/main/resources/templates/index.html
  src/main/resources/templates/profile.html
  src/main/resources/templates/updateProfile.html
Labels: enhancement

#208 노티스 리펙토링 fix0.2
  src/main/java/com/withus/withus/domain/club/entity/Club.java
  src/main/java/com/withus/withus/domain/comment/entity/Comment.java
  src/main/java/com/withus/withus/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/withus/withus/domain/notice/controller/NoticeController.java
  src/main/java/com/withus/withus/domain/notice/dto/NoticeResponseDto.java
  src/main/java/com/withus/withus/domain/notice/entity/Notice.java
  src/main/java/com/withus/withus/domain/notice/entity/ReportNotice.java
  src/main/java/com/withus/withus/domain/notice/repository/NoticeRepository.java
  src/main/java/com/withus/withus/domain/notice/service/NoticeServiceImpl.java
  src/main/java/com/withus/withus/global/scheduler/DeleteScheduler.java
  src/main/resources/templates/notice/noticeAdd.html
  src/test/java/com/withus/withus/notice/service/NoticeServiceImplTest.java
Labels: enhancement

#207 #32 카테고리 수정 영어에서 한글로 수정
  src/main/java/com/withus/withus/domain/club/dto/ClubRequestDto.java
  src/main/java/com/withus/withus/domain/club/dto/ClubResponseDto.java
  src/main/java/com/withus/withus/domain/club/entity/ClubCategory.java
  src/main/resources/static/css/clubpost.css
  src/main/resources/static/css/clubrevise.css
  src/main/resources/static/css/clubstyle.css
  src/main/resources/static/js/clubpost.js
  src/main/resources/static/js/clubrevise.js
  src/main/resources/templates/club/main-club.html
  src/main/resources/templates/club/post-club.html
  src/main/resources/templates/club/revise-club.html
Labels: enhancement

#213 refactor : 코드 리팩토링
  build.gradle
  src/main/java/com/withus/withus/domain/club/repository/ClubRepositoryQueryImpl.java
  src/main/java/com/withus/withus/domain/member/controller/MemberController.java
  src/main/java/com/withus/withus/domain/member/dto/PasswordRequestDto.java
  src/main/java/com/withus/withus/domain/member/dto/UpdateRequestDto.java
  src/main/java/com/withus/withus/domain/member/entity/Member.java
  src/main/java/com/withus/withus/domain/member/service/MemberServiceImpl.java
  src/main/java/com/withus/withus/domain/notification/dto/NotificationDto.java
  src/main/java/com/withus/withus/global/response/exception/GlobalExceptionHandler.java
  src/main/java/com/withus/withus/global/slack/SlackService.java
  src/main/resources/application.properties
  src/main/resources/static/favicon.ico
  src/test/java/com/withus/withus/member/service/MemberServiceImplIntegrationTest.java
Labels: refactor
